name: Deploy Service Gateway

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Build Project
              run: mvn clean install

            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Build docker image
              run: docker build -t luankenzley/gateway-service .
            - name: Push image docker
              run: docker push luankenzley/gateway-service

#    deploy:
#        needs: build
#        runs-on: self-hosted
#        steps:
#            - name: Pull image from docker hub
#              run: docker pull luankenzley/kitchen-gateway:latest
#            - name: Run docker container
#              run: docker run -d -p 8080:8080  -e HOST_MONGO=${{secrets.HOST_MONGO}} -e DATABASE_NAME_MONGO=${{secrets.DATABASE_NAME_MONGO}} --name deploy_gateway-service luankenzley/gateway-service
